### ISSUE TITLE
TypeError: ('name must be a string', Reshape{4}.0) in Step_3_train_CNN_normalisation.py

### ISSUE THREAD

**Issue by Tulika-opt** [stevenwudi/chalearn2014_wudi_lio#7]
Hello,
I have tried to run your prog,but in line no 205 of Step_3_train_CNN_normalisation.py an error:TypeError: ('name must be a string', Reshape{4}.0)  is being generated.I am using Theano's 1.0.1 ver,but I have also tried to run it in 0.9.0 but the result is the same.I am also providing a traceback of the error.
compiling train_model
Traceback (most recent call last):

  File "<ipython-input-39-7126b2513d0b>", line 212, in <module>
    on_unused_input='ignore')

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 449, in pfunc
    no_default_updates=no_default_updates)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 219, in rebuild_collect_shared
    cloned_v = clone_v_get_shared_updates(v, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)

  File "C:\Users\Public\New folder\lib\site-packages\theano\compile\pfunc.py", line 96, in clone_v_get_shared_updates
    [clone_d[i] for i in owner.inputs], strict=rebuild_strict)

  File "C:\Users\Public\New folder\lib\site-packages\theano\gof\graph.py", line 249, in clone_with_new_inputs
    new_node = self.clone()

  File "C:\Users\Public\New folder\lib\site-packages\theano\gof\graph.py", line 207, in clone
    [output.clone() for output in self.outputs])

  File "C:\Users\Public\New folder\lib\site-packages\theano\gof\graph.py", line 453, in clone
    cp = self.__class__(self.type, None, None, self.name)

  File "C:\Users\Public\New folder\lib\site-packages\theano\tensor\var.py", line 828, in __init__
    index=index, name=name)

  File "C:\Users\Public\New folder\lib\site-packages\theano\gof\graph.py", line 390, in __init__
    raise TypeError("name must be a string", name)

TypeError: ('name must be a string', Reshape{4}.0)

I would really appreciate the help.
Thanks

**Comment by RoboEvangelist** [comment]
I had the same problem, but it's been over a year since I solved it. So I don't remember the answer. They don't maintain this repository anymore, anyway.
I recommend new methods, such as TS-LSTM

**Comment by stevenwudi** [comment]
Yeah, thanks @RoboEvangelist for the comment. This repos is not under maintained. (Theano is not under maintained neither!).

I would suggest @Anktuliris give Pytorch a look (it's much user friendly and pythonic). Hence, the aforementioned algorithm is easier to be implemented. Also, End-to-End training with LSTM achieves better performance already. Good luck!
